### ISSUE TITLE
Boolean and null normalization support

### ISSUE THREAD

**Issue by macpreet** [zolekode/json-to-tables#2]
I tried to use your code. It reads null values in json and stores it in sql by replacing with NONE(python).  As per my requirement, we need null to be stored as it is in sql.
Any help would be appreciated.
Thanks

**Comment by samos667** [comment]
Exactly the same thing for me !

**Comment by samos667** [comment]
Exactly the same thing for me !

Some logs:
![image](https://user-images.githubusercontent.com/50653464/138187593-d2140ce2-34bf-4b2b-b9aa-3baad9497bfa.png)

json used: https://api.themoviedb.org/3/movie/500?api_key=<TMDB_API_KEY>

null value need to be None
true to True
false to False

@zolekode you know a method to fix it without rewrite the json ?

i will try some fix in my way, i'll keep you informed

**Comment by samos667** [comment]
@macpreet  i think* title need to be set to "Boolean and null normalization support"

**Comment by macpreet** [comment]
> @macpreet i thing title need to be set to "Boolean and null normalization support"

Done.

**Comment by macpreet** [comment]
Closed the issue by mistake . Sorry

**Comment by zolekode** [comment]
@samos667 regarding the screenshot you shared, you need to pass a dictionary (python dict) instead of a json. You will probably first need to do something like `import json   json.loads(your_json)`

**Comment by zolekode** [comment]
@macpreet @samos667 could you reexplain with the help of examples and screenshots? I am not very certain if I understand what you need.

**Comment by zolekode** [comment]
Issue should be fixed. @samos667 @macpreet 
- None is now cast to pure Nan which should save values as null
- Python bool objects are cast to pandas bool

To solve both your problems:
```python
table_maker.save_tables(..., cast_none_to_nan=True, cast_object_to_bool=True)
```

**Comment by zolekode** [comment]
Please leave a star and share the love of open source @samos667 @macpreet

**Comment by macpreet** [comment]
Thanks for your help @zolekode
